k8s_config:
- manifest_path: /yaml
  cluster_info:
    cluster_id: 4b983211-fdb6-53c7-9aba-f73153f4a27d
    cluster_name: Kay's Demo Cluster
- manifest_path: /yaml
  cluster_info:
    cluster_id: 16bb0016-3600-58d5-a4c2-a81856baac57
    cluster_name: Quote Demo cluster
