apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: quote-backend
  namespace: ambassador
  labels: null
  annotations: {}
spec:
  ambassador_id:
  - default
  docs:
    path: /.ambassador-internal/openapi-docs
  hostname: "*"
  prefix: /backend/
  service: quote
  connect_timeout_ms: 30
