apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: quote-backend
  namespace: demo
  labels:
    argocd.argoproj.io/instance: quote
  annotations: {}
spec:
  ambassador_id:
  - default
  hostname: demo.kjames.k736.net
  prefix: /backend/hello/
  service: quote.default:80
  connect_timeout_ms: 3000
