apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  annotations: {}
  name: quote-backend
  namespace: demo
spec:
  ambassador_id:
  - default
  hostname: demo.kjames.k736.net
  prefix: /backend/hello/
  service: quote.default:80
---
apiVersion: getambassador.io/v3alpha1
kind: RateLimit
metadata:
  name: rate-limit-for-quote-backend
  namespace: demo
spec:
  domain: ambassador
  limits:
  - action: Enforce
    pattern:
    - generic_key: quote-backend
    - remote_address: "*"
    rate: 50
    unit: minute
    burstFactor: 1
