apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: web-mapping
  namespace: default
  labels: null
  annotations: {}
spec:
  ambassador_id:
  - default
  cors:
    origins:
    - http://demo.kjames.k736.net
  hostname: demo.kjames.k736.net
  prefix: /
  service: quotefrontend
  retry_policy:
    retry_on: 5xx
    num_retries: 1
    per_try_timeout: 150ms
