apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  annotations: {}
  name: quote-backend
  namespace: demo
spec:
  ambassador_id:
  - default
  hostname: demo.kjames.k736.net
  labels:
    ambassador:
    - header_request_label:
      - request_headers:
          header_name: x-token-name
          key: headerkey
  prefix: /backend-2/
  service: quote.default:80
