apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  annotations: {}
  name: quote-backend
  namespace: demo
spec:
  ambassador_id:
  - default
  hostname: demo.kjames.k736.net
  labels:
    ambassador:
    - header_request_label:
      - request_headers:
          header_name: x-token-name
          key: headerkey
  prefix: /backend/
  service: quote.default:80
  retry_policy:
    retry_on: 5xx
    num_retries: 1
    per_try_timeout: NaNms
