apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  annotations: {}
  name: quote-backend
  namespace: demo
spec:
  ambassador_id:
  - default
  hostname: "*"
  prefix: /backend/hello/
  service: quote.default:80
  retry_policy:
    retry_on: 5xx
    num_retries: 1
    per_try_timeout: 150ms
  timeout_ms: 3000
