apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  annotations: {}
  name: quote-backend
  namespace: demo
spec:
  ambassador_id:
  - default
  hostname: "*"
  prefix: /backend/hello/
  service: quote.default:80
  connect_timeout_ms: 3000
