---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: keycloak
spec:
  hostname: "keycloak1.kjames.k736.net"
  prefix: /
  service: keycloak:8080
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: keycloak-host
spec:
  hostname: "keycloak1.kjames.k736.net"
  acmeProvider:
    email: marekomgmt@gmail.com
